name: CI/CD

on: 
  push:
    branches: 
      - 3Gteam

jobs:
  build:
    runs-on : ubuntu-latest
    
    steps:        
      - name : Clone repository into git vm
        uses: actions/checkout@v1
        
      - name : Setup jdk
        uses : actions/setup-java@v1
        with:
          java-version: 11
        
      - name : Create jar file for project
        run : mvn clean install
    
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/edumanagement.jar
  
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
          
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21

        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: false
          application_name: eduManagement
          environment_name: Edumanagement-devEnv
          version_label:  "Version ${{ github.run_number }}"
          region: eu-north-1
          deployment_package: edumanagement.jar
